version: 1

update_configs:
  - package_manager: "go:modules"
    directory: "/"
    update_schedule: "daily"
    default_reviewers:
      - chrisns
    default_assignees:
      - chrisns
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: security:patch
