name: CI Pipeline
on:
  push:
    paths-ignore:
      - README.md
    branches:
      - "**"
    tags-ignore:
      - build-refs**
  pull_request:

env:
  HUB_VERSION: 2.12.7
  HUB_OS: darwin
  HUB_ARCH: amd64

jobs:
  release-name:
    name: Generate a release name to use
    runs-on: ubuntu-latest
    steps:
      - run: echo $GITHUB_REF | sed -e 's/.*\///g' > VERSION
      - uses: actions/upload-artifact@v1
        with:
          name: VERSION
          path: VERSION

  secret-check:
    name: Secret check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: docker://zricethezav/gitleaks
        with:
          args: -v --exclude-forks --repo-path=. --repo-config

  golangci-lint:
    name: GolangCI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: docker://golangci/golangci-lint
        with:
          args: golangci-lint run --color=always

  test-build-publish:
    name: Test and Build
    runs-on: macOS-latest
    needs: release-name
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        OS:
          - darwin
          - linux
          - windows
          - netbsd
          - freebsd
          - openbsd
          - plan9
          - solaris
        ARCH:
          - amd64
          - 386
          - arm64
          - arm
        include:
          - OS: windows
            EXT: .exe
        exclude:
          - OS: darwin
            ARCH: arm64
          - OS: darwin
            ARCH: arm
          - OS: windows
            ARCH: arm64
          - OS: freebsd
            ARCH: arm64
          - OS: plan9
            ARCH: arm64
          - OS: solaris
            ARCH: arm64
          - OS: solaris
            ARCH: arm
          - OS: solaris
            ARCH: 386
    env:
      BUILD_FILENAME: kubectl-passman-${{matrix.OS}}-${{matrix.ARCH}}${{matrix.EXT}}
      ZIP_FILENAME: kubectl-passman-${{matrix.OS}}-${{matrix.ARCH}}.zip
    steps:
      - uses: actions/checkout@v1
      - run: go test -v
      - run: go build -a -o ${BUILD_FILENAME}
        env:
          GOOS: ${{matrix.OS}}
          GOARCH: ${{matrix.ARCH}}
      - run: chmod +x ${BUILD_FILENAME}
        env:
          GOOS: ${{matrix.OS}}
          GOARCH: ${{matrix.ARCH}}
      - uses: actions/upload-artifact@v1
        with:
          name: kubectl-passman-${{matrix.OS}}-${{matrix.ARCH}}${{matrix.EXT}}
          path: kubectl-passman-${{matrix.OS}}-${{matrix.ARCH}}${{matrix.EXT}}
      - name: fetch hub
        if: github.event_name == 'push'
        run: wget -q -c https://github.com/github/hub/releases/download/v${HUB_VERSION}/hub-${HUB_OS}-${HUB_ARCH}-${HUB_VERSION}.tgz -O - | tar -xz
      - uses: actions/download-artifact@v1
        with:
          name: VERSION
      - name: create pre-release if it doesn't exist
        if: github.event_name == 'push'
        run: hub-${HUB_OS}-${HUB_ARCH}-${HUB_VERSION}/bin/hub release create -p -m "Latest build of ${{github.ref}}" "$(cat VERSION/VERSION)" || echo release already exists
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: zip kubectl-passman-${{matrix.OS}}-${{matrix.ARCH}}.zip ${BUILD_FILENAME}
      - name: Publish to release
        if: github.event_name == 'push'
        run: |
          hub-${HUB_OS}-${HUB_ARCH}-${HUB_VERSION}/bin/hub release edit -a ${ZIP_FILENAME} -m "Latest build of ${{github.ref}}" "$(cat VERSION/VERSION)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  write-krew:
    name: Write krew manifest file
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    env:
      HUB_OS: linux
    needs:
      - test-build-publish
    steps:
      - uses: actions/checkout@v1
      - run: wget -q -c https://github.com/github/hub/releases/download/v${HUB_VERSION}/hub-${HUB_OS}-${HUB_ARCH}-${HUB_VERSION}.tgz -O - | tar -xz
      - uses: actions/download-artifact@v1
        with:
          name: VERSION
      - run: hub-linux-amd64-2.12.7/bin/hub release download "$(cat VERSION/VERSION)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: krew/generate-shas.sh > krew/shas.yaml
      - name: template krew manifest
        run: |
          go get github.com/yngveh/sprig-cli
          VERSION=$(cat VERSION/VERSION) $(go env GOPATH)/bin/sprig-cli -tmpl krew/krew.tpl -data krew/shas.yaml > passman.yaml
      - name: show krew manifest
        run: cat passman.yaml
      - uses: actions/upload-artifact@v1
        with:
          name: passman.yaml
          path: passman.yaml
      - name: Publish krew manifest to release
        run: hub-${HUB_OS}-${HUB_ARCH}-${HUB_VERSION}/bin/hub release edit -a passman.yaml -m "Latest build of ${{github.ref}}" "$(cat VERSION/VERSION)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
