name: CI Pipeline
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: docker pull
        run: docker pull golang:1.13 
      - name: test
        run: docker run --rm -v `pwd`:/app -w /app golang:1.13 go test -v
