name: CI Pipeline
on: [push]

jobs:
  go-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: docker://cytopia/golint
        with:
          args: .

  go-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: docker://cytopia/gofmt
        with:
          args: --ci .

  go-imports:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: docker://cytopia/goimports
        with:
          args: --ci .

  go-vet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: docker://golang:1.13
        with:
          args: go vet

  go-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: docker://golang:1.13
        with:
          args: docker run --rm -v `pwd`:/app -w /app golang:1.13 go test -v

  go-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 30
      matrix:
        GOOS:
          [
            windows,
            linux,
            darwin,
            solaris,
            freebsd,
            netbsd,
            openbsd,
            dragonfly,
            plan9,
            nacl,
            android,
          ]
        GOARCH: [amd64, arm64, "386", arm, ppc64, ppc64le, amd64p32]
    steps:
      - uses: actions/checkout@v1
      - uses: docker://golang:1.13
        with:
          args: go build -a -o kubectl-${{ matrix.GOOS }}-${{ matrix.GOARCH }}
        env:
          GOOS: ${{ matrix.GOOS }}
          GOARCH: ${{ matrix.GOARCH }}
