name: CI Pipeline
on: [push, pull_request]

jobs:
  secret-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: docker://cdssnc/seekret-github-action
      - uses: "eshork/gitleaks-action@master"

  go-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: docker://cytopia/golint
        with:
          args: .

  go-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: docker://cytopia/gofmt
        with:
          args: --ci .

  go-imports:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: docker://cytopia/goimports
        with:
          args: --ci .

  go-vet:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - run: go vet

  go-test:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - run: go test -v

  go-build:
    runs-on: macOS-latest
    strategy:
      fail-fast: false
      max-parallel: 30
      matrix:
        GOOS:
          # - windows
          # - linux
          - darwin
          # - solaris
          # - freebsd
          # - netbsd
          # - openbsd
          # - dragonfly
          # - plan9
          # - nacl
          # - android
        GOARCH:
          - amd64
          # - arm64
          # - "386"
          # - arm
          # - ppc64
          # - ppc64le
          # - amd64p32
    steps:
      - uses: actions/checkout@v1
      - run: |
          go build -a -o kubectl-${{ matrix.GOOS }}-${{ matrix.GOARCH }}
        env:
          GOOS: ${{ matrix.GOOS }}
          GOARCH: ${{ matrix.GOARCH }}
  # go-build:
  #   strategy:
  #     matrix:
  #       targets:
  #         - windows/386
  #         - windows/amd64
  #         - linux/386
  #         - linux/amd64
  #         - darwin/386
  #         - darwin/amd64
  #       go_version:
  #         - 1.13.x
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v1
  #     - run: |
  #       go get github.com/karalabe/xgo
  #     - uses: crazy-max/ghaction-xgo@master
  #       with:
  #         go_version: ${{ matrix.go_version }}
  #         prefix: myapp
  #         targets: ${{ matrix.target }}
  #         v: true
  #         x: false
  #         ldflags: -s -w
